export const APP_NAME = 'ACT Innovation Ecosystem Navigator'
export const APP_DESCRIPTION =
  'Discover innovation support organisations, programs, grants, spaces, and networks across the Australian Capital Territory.'
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://act-navigator.gov.au'

export const PAGE_SIZE = 20
export const SEARCH_SUGGEST_LIMIT = 8
export const RELATED_ENTITIES_LIMIT = 6
export const FEATURED_ENTITIES_LIMIT = 6

export const ACT_SUBURBS = [
  'Acton',
  'Ainslie',
  'Amaroo',
  'Aranda',
  'Banks',
  'Barton',
  'Belconnen',
  'Bonner',
  'Braddon',
  'Bruce',
  'Campbell',
  'Casey',
  'Chifley',
  'Civic',
  'City',
  'Conder',
  'Curtin',
  'Deakin',
  'Dickson',
  'Downer',
  'Dunlop',
  'Evatt',
  'Farrer',
  'Florey',
  'Flynn',
  'Fyshwick',
  'Gungahlin',
  'Hackett',
  'Hawker',
  'Hughes',
  'Hume',
  'Isaacs',
  'Jamison',
  'Kingston',
  'Kippax',
  'Latham',
  'Lyons',
  'Macgregor',
  'Macquarie',
  'Manuka',
  'Mitchell',
  'Molonglo',
  'Ngunnawal',
  'Nicholls',
  'O\'Connor',
  'Oaks Estate',
  'Palmerston',
  'Parkes',
  'Pearce',
  'Phillip',
  'Pialligo',
  'Reid',
  'Scullin',
  'Spence',
  'Stirling',
  'Taylor',
  'Theodore',
  'Throsby',
  'Torrens',
  'Tuggeranong',
  'Turner',
  'Wanniassa',
  'Watson',
  'Weston Creek',
  'Woden',
  'Wright',
  'Yarralumla',
]

export const ACT_PRECINCTS = [
  'City / Civic',
  'Braddon / Inner North',
  'Acton / ANU',
  'Barton / Parkes',
  'Kingston / Manuka',
  'Fyshwick',
  'Mitchell',
  'Bruce / Belconnen',
  'Gungahlin',
  'Woden / Phillip',
  'Tuggeranong',
  'Molonglo',
  'Black Mountain',
  'Queanbeyan',
]
